using NUnit.Framework;
using TradeKit.Core.AlgoBase;
using TradeKit.Core.Common;
using TradeKit.Core.ElliottWave;
using TradeKit.Core.Json;
using TradeKit.Core.PatternGeneration;

namespace TradeKit.Tests
{
    public class ExactMarkupTests
    {
        private PatternGenerator m_PatternGenerator;
        private static readonly ITimeFrame TIME_FRAME = TimeFrameHelper.Minute5;

        private class TestBarsProvider : IBarsProvider
        {
            private readonly List<JsonCandleExport> m_Candles;
            public TestBarsProvider(List<JsonCandleExport> candles)
            {
                m_Candles = candles;
            }

            public int Count => m_Candles.Count;
            public int StartIndexLimit => 0;
            public ITimeFrame TimeFrame => TIME_FRAME;
            public ISymbol BarSymbol => new SymbolBase("TEST", "Test Symbol", 0, 5, 0.0001, 1, 100000);

            public event EventHandler BarClosed { add { } remove { } }
            public double GetClosePrice(int index) => m_Candles[index].C;
            public double GetHighPrice(int index) => m_Candles[index].H;
            public int GetIndexByTime(DateTime dateTime) => m_Candles.FindIndex(c => c.OpenDate == dateTime);
            public double GetLowPrice(int index) => m_Candles[index].L;
            public double GetMedianPrice(int index) => (m_Candles[index].H + m_Candles[index].L) / 2;
            public double GetOpenPrice(int index) => m_Candles[index].O;
            public DateTime GetOpenTime(int index) => m_Candles[index].OpenDate;
            public void LoadBars(DateTime date) { }
            public void Dispose() { }
        }

        [SetUp]
        public void Setup()
        {
            m_PatternGenerator = new PatternGenerator(true);
        }

        /// <summary>
        /// Builds the list of BarPoints from a generated ModelPattern for use with ElliottWaveExactMarkup.
        /// Extracts main-level key points (level == model.Level) plus the pattern start point.
        /// </summary>
        private static List<BarPoint> BuildPointsFromModel(ModelPattern model, IBarsProvider barsProvider)
        {
            List<PatternKeyPoint> allKeyPoints = model.PatternKeyPoints
                .SelectMany(x => x.Value)
                .OrderBy(x => x.Index)
                .ToList();

            List<PatternKeyPoint> mainWaves = allKeyPoints
                .Where(x => x.Notation.Level == model.Level)
                .OrderBy(x => x.Index)
                .ToList();

            if (mainWaves.Count == 0)
                return new List<BarPoint>();

            PatternKeyPoint endNode = mainWaves.Last();
            bool isUp = endNode.Value > model.Candles[0].O;

            double startVal = isUp
                ? model.Candles.Take(mainWaves[0].Index + 1).Min(x => x.L)
                : model.Candles.Take(mainWaves[0].Index + 1).Max(x => x.H);

            int startIndex = model.Candles.FindIndex(
                x => Math.Abs(x.L - startVal) < double.Epsilon
                  || Math.Abs(x.H - startVal) < double.Epsilon);
            if (startIndex < 0)
                startIndex = 0;

            var points = new List<BarPoint>
            {
                new BarPoint(startVal, model.Candles[startIndex].OpenDate, barsProvider)
            };

            List<PatternKeyPoint> distinctPoints = allKeyPoints
                .Where(x => x.Index > startIndex && x.Index <= endNode.Index)
                .GroupBy(x => x.Index)
                .Select(g => g.OrderByDescending(x => x.Notation.Level).First())
                .OrderBy(x => x.Index)
                .ToList();

            foreach (PatternKeyPoint kp in distinctPoints)
                points.Add(new BarPoint(kp.Value, model.Candles[kp.Index].OpenDate, barsProvider));

            return points;
        }

        /// <summary>
        /// Generates <paramref name="totalTests"/> patterns of the given model type, runs
        /// ElliottWaveExactMarkup.Parse on the ideal key-points, and asserts that at least
        /// <paramref name="threshold"/> fraction of runs correctly identify the model.
        /// <para>
        /// Some model pairs are structurally indistinguishable in v1 (no sub-wave analysis):
        /// <list type="bullet">
        /// <item>DIAGONAL_CONTRACTING_INITIAL and DIAGONAL_CONTRACTING_ENDING share identical
        /// 5-wave price structure (both generated by the same GetDiagonal logic). They can only
        /// be distinguished by their sub-wave models (IMPULSE vs ZIGZAG inner waves), which is
        /// not evaluated in v1. Use <paramref name="acceptedTypes"/> to accept both.</item>
        /// <item>ZIGZAG and DOUBLE_ZIGZAG have the same 3-wave price structure and identical
        /// Fibonacci scoring in v1. Without parent context, both are valid interpretations.
        /// Use <paramref name="acceptedTypes"/> to accept both.</item>
        /// </list>
        /// </para>
        /// </summary>
        private void RunMarkupTest(
            ElliottModelType modelType,
            int totalTests = 20,
            int minBars = 200,
            double threshold = 0.6,
            ElliottModelType[]? acceptedTypes = null)
        {
            int matchedTests = 0;
            HashSet<ElliottModelType> accepted = acceptedTypes != null
                ? new HashSet<ElliottModelType>(acceptedTypes) { modelType }
                : new HashSet<ElliottModelType> { modelType };

            for (int i = 0; i < totalTests; i++)
            {
                (DateTime start, DateTime end) = Helper.GetDateRange(minBars, TIME_FRAME);
                PatternArgsItem paramArgs = new PatternArgsItem(40, 60, start, end, TIME_FRAME);

                // FLAT and TRIANGLE generators require room for the B-wave overshoot (B exceeds
                // the pattern origin) and for triangle wave A to extend beyond the endpoint.
                // PatternArgsItem sets Min=StartValue and Max=EndValue by default, which causes
                // the generator to fall back to Zigzag. Extend the price buffer so the generator
                // can produce genuine FLAT/TRIANGLE patterns.
                switch (modelType)
                {
                    case ElliottModelType.FLAT_EXTENDED:
                    case ElliottModelType.FLAT_RUNNING:
                    case ElliottModelType.TRIANGLE_CONTRACTING:
                    case ElliottModelType.TRIANGLE_RUNNING:
                        paramArgs.Min -= paramArgs.Range;
                        paramArgs.Max += paramArgs.Range;
                        break;
                }

                ModelPattern model = m_PatternGenerator.GetPattern(paramArgs, modelType);

                if (model.Candles.Count < 2)
                    continue;

                var barsProvider = new TestBarsProvider(model.Candles);
                List<BarPoint> points = BuildPointsFromModel(model, barsProvider);

                if (points.Count < 2)
                    continue;

                var markup = new ElliottWaveExactMarkup();
                List<ExactParsedNode> results = markup.Parse(points);
                ExactParsedNode? bestResult = results.FirstOrDefault();

                // Accept if the correct model appears anywhere in results with the right
                // wave count — meaning the hard rules were satisfied for the generated data.
                // Fibonacci ratios only affect ranking, not identification; a flat with
                // B/A=1.0 is valid (hard rules pass) even if it scores lower than a zigzag.
                ExactParsedNode? matchedResult = results.FirstOrDefault(
                    r => accepted.Contains(r.ModelType) && r.WaveCount == r.ExpectedWaves);
                bool matched = matchedResult != null;

                if (matched)
                {
                    matchedTests++;
                }
                else
                {
                    Console.WriteLine(
                        $"[{modelType}] run {i}: best={bestResult?.ModelType} " +
                        $"score={bestResult?.Score:F3} waves={bestResult?.WaveCount}/{bestResult?.ExpectedWaves}" +
                        $" | no {modelType} in results ({results.Count} total)");
                }
            }

            int minRequired = (int)Math.Ceiling(totalTests * threshold);
            Assert.IsTrue(
                matchedTests >= minRequired,
                $"[{modelType}] only {matchedTests}/{totalTests} runs matched " +
                $"(required ≥ {minRequired}, threshold {threshold:P0}).");
        }

        [Test]
        public void ImpulseExactMarkupTest() =>
            RunMarkupTest(ElliottModelType.IMPULSE, minBars: 300);

        [Test]
        public void DiagonalInitialExactMarkupTest() =>
            // INITIAL and ENDING share identical 5-wave price structure in v1;
            // both are accepted since they cannot be distinguished without sub-wave analysis.
            RunMarkupTest(ElliottModelType.DIAGONAL_CONTRACTING_INITIAL, minBars: 300,
                acceptedTypes: new[] { ElliottModelType.DIAGONAL_CONTRACTING_ENDING });

        [Test]
        public void DiagonalEndingExactMarkupTest() =>
            // INITIAL and ENDING share identical 5-wave price structure in v1;
            // both are accepted since they cannot be distinguished without sub-wave analysis.
            RunMarkupTest(ElliottModelType.DIAGONAL_CONTRACTING_ENDING, minBars: 300,
                acceptedTypes: new[] { ElliottModelType.DIAGONAL_CONTRACTING_INITIAL });

        [Test]
        public void ZigzagExactMarkupTest() =>
            // ZIGZAG and DOUBLE_ZIGZAG share identical 3-wave price structure and Fibonacci
            // scoring in v1; without parent context both are valid interpretations.
            RunMarkupTest(ElliottModelType.ZIGZAG, minBars: 200,
                acceptedTypes: new[] { ElliottModelType.DOUBLE_ZIGZAG });

        [Test]
        public void DoubleZigzagExactMarkupTest() =>
            // DOUBLE_ZIGZAG and ZIGZAG are indistinguishable in v1 (same 3-wave structure,
            // same Fibonacci maps). Without parent context, both are valid interpretations.
            RunMarkupTest(ElliottModelType.DOUBLE_ZIGZAG, minBars: 200,
                acceptedTypes: new[] { ElliottModelType.ZIGZAG });

        [Test]
        public void FlatExtendedExactMarkupTest() =>
            RunMarkupTest(ElliottModelType.FLAT_EXTENDED, minBars: 200);

        [Test]
        public void FlatRunningExactMarkupTest() =>
            RunMarkupTest(ElliottModelType.FLAT_RUNNING, minBars: 200);

        [Test]
        public void TriangleContractingExactMarkupTest() =>
            RunMarkupTest(ElliottModelType.TRIANGLE_CONTRACTING, minBars: 300);

        [Test]
        public void TriangleRunningExactMarkupTest() =>
            RunMarkupTest(ElliottModelType.TRIANGLE_RUNNING, minBars: 300);

        /// <summary>
        /// Generates a zigzag pattern built from specific sub-wave model types
        /// (A = IMPULSE, B = TRIANGLE_CONTRACTING, C = DIAGONAL_CONTRACTING_ENDING),
        /// runs the recursive markup, and verifies both the top-level model and that
        /// each sub-wave is identified as one of the expected types.
        /// </summary>
        [Test]
        public void ZigzagCompositeSubWaveMarkupTest()
        {
            const int totalTests = 10;
            int matchedTopLevel = 0;
            int matchedWaveA    = 0;
            int matchedWaveC    = 0;

            // Accepted sub-model sets: anything TargetModels supports for each position
            var acceptedA = new HashSet<ElliottModelType>
            {
                ElliottModelType.IMPULSE,
                ElliottModelType.DIAGONAL_CONTRACTING_INITIAL,
                ElliottModelType.DIAGONAL_CONTRACTING_ENDING
            };
            var acceptedC = new HashSet<ElliottModelType>
            {
                ElliottModelType.IMPULSE,
                ElliottModelType.DIAGONAL_CONTRACTING_ENDING,
                ElliottModelType.DIAGONAL_CONTRACTING_INITIAL
            };
            for (int run = 0; run < totalTests; run++)
            {
                // 600 bars: each of 3 ZIGZAG sub-waves gets ~200 bars; their sub-waves
                // get ~40 bars each (< SIMPLE_BARS_THRESHOLD=100) so recursion stops at
                // level 2 → ~18 distinct key points total → parse stays fast.
                (DateTime start, DateTime end) = Helper.GetDateRange(600, TIME_FRAME);
                PatternArgsItem args = new PatternArgsItem(40, 60, start, end, TIME_FRAME);
                args.Min -= args.Range;
                args.Max += args.Range;

                ModelPattern model = m_PatternGenerator.GetZigzagComposite(
                    args,
                    ElliottModelType.IMPULSE,
                    ElliottModelType.TRIANGLE_CONTRACTING,
                    ElliottModelType.DIAGONAL_CONTRACTING_ENDING);

                if (model.Candles.Count < 2) continue;

                var barsProvider = new TestBarsProvider(model.Candles);
                List<BarPoint> points = BuildPointsFromModel(model, barsProvider);
                if (points.Count < 2) continue;

                // Use no barsProvider so direction/candle hard rules are skipped
                // (same as existing tests — synthetic point data only).
                var markup = new ElliottWaveExactMarkup();
                List<ExactParsedNode> results = markup.Parse(points);

                // Look for ZIGZAG specifically — DOUBLE_ZIGZAG can score higher because its
                // W/Y sub-waves (ZIGZAG) are easier to identify than IMPULSE/DIAGONAL.
                ExactParsedNode best = results.FirstOrDefault(
                    r => r.ModelType == ElliottModelType.ZIGZAG
                         && r.WaveCount == r.ExpectedWaves);

                if (best == null)
                {
                    Console.WriteLine(
                        $"[ZigzagComposite] run {run}: no ZIGZAG top={results.FirstOrDefault()?.ModelType}");
                    continue;
                }
                matchedTopLevel++;

                // Wave A (index 0): expected IMPULSE / DIAGONAL variants
                ElliottModelType waveAType = best.SubWaves?[0]?.ModelType
                    ?? ElliottModelType.SIMPLE_IMPULSE;
                if (acceptedA.Contains(waveAType))
                    matchedWaveA++;
                else
                    Console.WriteLine(
                        $"[ZigzagComposite] run {run}: wave A = {waveAType}");

                // Wave C (index 2): expected IMPULSE / DIAGONAL variants
                ElliottModelType waveCType = best.SubWaves?.Length >= 3
                    ? best.SubWaves[2]?.ModelType ?? ElliottModelType.SIMPLE_IMPULSE
                    : ElliottModelType.SIMPLE_IMPULSE;
                if (acceptedC.Contains(waveCType))
                    matchedWaveC++;
                else
                    Console.WriteLine(
                        $"[ZigzagComposite] run {run}: wave C = {waveCType}");
            }

            int minTopRequired = (int)Math.Ceiling(totalTests * 0.6);
            Assert.IsTrue(matchedTopLevel >= minTopRequired,
                $"[ZigzagComposite] top-level: {matchedTopLevel}/{totalTests} " +
                $"(required ≥ {minTopRequired}).");

            // Combined A+C identifications must reach 40% of top-level matches
            // (A and C have identical price structure to SIMPLE_IMPULSE in degenerate cases,
            //  so a soft combined threshold is the right check here).
            if (matchedTopLevel > 0)
            {
                int minSubRequired = (int)Math.Ceiling(matchedTopLevel * 0.4);
                Assert.IsTrue((matchedWaveA + matchedWaveC) >= minSubRequired,
                    $"[ZigzagComposite] combined sub-wave A+C identification too low: " +
                    $"A={matchedWaveA}, C={matchedWaveC}, sum={matchedWaveA + matchedWaveC} " +
                    $"of {matchedTopLevel} top-level matches (required ≥ {minSubRequired}).");
            }
        }
        /// <summary>
        /// Recursively verifies that all adjacent sub-waves of <paramref name="node"/> are
        /// continuous: the end bar index of sub-wave i must equal the start bar index of
        /// sub-wave i+1 (§4.1-continuity hard rule).
        /// </summary>
        private static void AssertSubWaveContinuity(ExactParsedNode? node, string context)
        {
            if (node?.SubWaves == null || node.WaveCount < 2) return;

            for (int i = 0; i + 1 < node.WaveCount; i++)
            {
                ExactParsedNode sw     = node.SubWaves[i];
                ExactParsedNode swNext = node.SubWaves[i + 1];
                if (sw == null || swNext == null) continue;

                Assert.AreEqual(
                    sw.EndPoint.BarIndex,
                    swNext.StartPoint.BarIndex,
                    $"[{context}] {node.ModelType}: sub-wave {i + 1} end bar " +
                    $"({sw.EndPoint.BarIndex}) must equal sub-wave {i + 2} start bar " +
                    $"({swNext.StartPoint.BarIndex}) — §4.1-continuity.");

                AssertSubWaveContinuity(sw, context);
            }

            // Recurse into the last sub-wave as well
            AssertSubWaveContinuity(node.SubWaves[node.WaveCount - 1], context);
        }

        /// <summary>
        /// Recursively verifies that every <see cref="ElliottModelType.SIMPLE_IMPULSE"/>
        /// segment at any tree depth is "contained" — all candles within the segment's bar
        /// range stay inside the [startPrice, endPrice] corridor (§4.1-simple-impulse).
        /// The hard rule now fires at ALL recursion depths (not just the last level).
        /// </summary>
        private static void AssertSimpleImpulseContainment(
            ExactParsedNode? node, TestBarsProvider provider, string context, int treeLevel = 0)
        {
            if (node?.SubWaves == null) return;

            int subLevel = treeLevel + 1;

            for (int i = 0; i < node.WaveCount; i++)
            {
                ExactParsedNode sw = node.SubWaves[i];
                if (sw == null) continue;

                if (sw.ModelType == ElliottModelType.SIMPLE_IMPULSE)
                {
                    // §4.1-simple-impulse fires at ALL depths when a barsProvider is present.
                    bool isUp     = sw.EndPoint.Value > sw.StartPoint.Value;
                    double startP = sw.StartPoint.Value;
                    double endP   = sw.EndPoint.Value;
                    int from      = Math.Min(sw.StartPoint.BarIndex, sw.EndPoint.BarIndex);
                    int to        = Math.Max(sw.StartPoint.BarIndex, sw.EndPoint.BarIndex);

                    for (int bar = from; bar <= to; bar++)
                    {
                        if (bar < 0 || bar >= provider.Count) continue;

                        if (isUp)
                        {
                            Assert.LessOrEqual(provider.GetHighPrice(bar), endP,
                                $"[{context}] Upward SIMPLE_IMPULSE bar {bar}: " +
                                $"High={provider.GetHighPrice(bar):F5} > endPrice={endP:F5}");
                            Assert.GreaterOrEqual(provider.GetLowPrice(bar), startP,
                                $"[{context}] Upward SIMPLE_IMPULSE bar {bar}: " +
                                $"Low={provider.GetLowPrice(bar):F5} < startPrice={startP:F5}");
                        }
                        else
                        {
                            Assert.GreaterOrEqual(provider.GetLowPrice(bar), endP,
                                $"[{context}] Downward SIMPLE_IMPULSE bar {bar}: " +
                                $"Low={provider.GetLowPrice(bar):F5} < endPrice={endP:F5}");
                            Assert.LessOrEqual(provider.GetHighPrice(bar), startP,
                                $"[{context}] Downward SIMPLE_IMPULSE bar {bar}: " +
                                $"High={provider.GetHighPrice(bar):F5} > startPrice={startP:F5}");
                        }
                    }
                }
                else
                {
                    AssertSimpleImpulseContainment(sw, provider, context, subLevel);
                }
            }
        }

        /// <summary>
        /// Generates multi-level composite patterns, runs markup with a real
        /// <see cref="TestBarsProvider"/> and asserts the §4.1-simple-impulse invariant:
        /// every <see cref="ElliottModelType.SIMPLE_IMPULSE"/> sub-wave returned in any
        /// result must have all its candles contained within the segment's price corridor.
        /// </summary>
        [Test]
        public void SimpleImpulseContainmentPropertyTest()
        {
            const int totalRuns = 5;

            for (int run = 0; run < totalRuns; run++)
            {
                // 1000 bars: each sub-wave gets ~330 bars, their sub-waves ~66 bars
                // (< SIMPLE_BARS_THRESHOLD) → depth=2 key points only → ~18 total points.
                // With barsProvider, containment pruning keeps parse fast.
                (DateTime start, DateTime end) = Helper.GetDateRange(1000, TIME_FRAME);
                PatternArgsItem args = new PatternArgsItem(40, 60, start, end, TIME_FRAME);
                args.Min -= args.Range;
                args.Max += args.Range;

                ModelPattern model = m_PatternGenerator.GetZigzagComposite(
                    args,
                    ElliottModelType.IMPULSE,
                    ElliottModelType.TRIANGLE_CONTRACTING,
                    ElliottModelType.DIAGONAL_CONTRACTING_ENDING);

                if (model.Candles.Count < 2) continue;

                var barsProvider = new TestBarsProvider(model.Candles);
                List<BarPoint> points = BuildPointsFromModel(model, barsProvider);
                if (points.Count < 2) continue;

                // Run with barsProvider so candle-level rules are enforced.
                var markup = new ElliottWaveExactMarkup(barsProvider);
                List<ExactParsedNode> results = markup.Parse(points);

                foreach (ExactParsedNode result in results)
                    AssertSimpleImpulseContainment(result, barsProvider,
                        $"run {run} / {result.ModelType}");
            }
        }

        /// <summary>
        /// Verifies the §3.8-depth-filter hard rule: every result returned by
        /// <see cref="ElliottWaveExactMarkup.Parse"/> must have
        /// <see cref="ExactParsedNode.GetDepth"/> ≥ <see cref="ElliottWaveExactMarkup.MIN_RESULT_DEPTH"/>.
        /// </summary>
        [Test]
        public void AllResultsMeetMinDepthTest()
        {
            var modelsToTest = new[]
            {
                ElliottModelType.IMPULSE,
                ElliottModelType.ZIGZAG,
                ElliottModelType.FLAT_EXTENDED,
                ElliottModelType.TRIANGLE_CONTRACTING,
            };

            foreach (ElliottModelType modelType in modelsToTest)
            {
                (DateTime start, DateTime end) = Helper.GetDateRange(400, TIME_FRAME);
                var args = new PatternArgsItem(40, 60, start, end, TIME_FRAME);

                if (modelType is ElliottModelType.FLAT_EXTENDED
                              or ElliottModelType.TRIANGLE_CONTRACTING)
                {
                    args.Min -= args.Range;
                    args.Max += args.Range;
                }

                ModelPattern model = m_PatternGenerator.GetPattern(args, modelType);
                if (model.Candles.Count < 2) continue;

                var barsProvider = new TestBarsProvider(model.Candles);
                List<BarPoint> points = BuildPointsFromModel(model, barsProvider);
                if (points.Count < 2) continue;

                var markup = new ElliottWaveExactMarkup(barsProvider);
                List<ExactParsedNode> results = markup.Parse(points);

                foreach (ExactParsedNode result in results)
                {
                    int depth = result.GetDepth();
                    Assert.GreaterOrEqual(
                        depth, ElliottWaveExactMarkup.MIN_RESULT_DEPTH,
                        $"[{modelType}] result {result.ModelType} has GetDepth()={depth} " +
                        $"< MIN_RESULT_DEPTH={ElliottWaveExactMarkup.MIN_RESULT_DEPTH} " +
                        $"— §3.8-depth-filter violated.");
                }
            }
        }

        /// <summary>
        /// Generates patterns of several types and verifies that every parsed node in the
        /// result tree satisfies the §4.1-continuity hard rule: adjacent sub-waves at the
        /// same rank must be continuous (no gap between end of wave i and start of wave i+1).
        /// </summary>
        [Test]
        public void SubWaveContinuityStructuralTest()
        {
            var modelsToTest = new[]
            {
                ElliottModelType.IMPULSE,
                ElliottModelType.ZIGZAG,
                ElliottModelType.FLAT_EXTENDED,
                ElliottModelType.TRIANGLE_CONTRACTING,
            };

            foreach (ElliottModelType modelType in modelsToTest)
            {
                (DateTime start, DateTime end) = Helper.GetDateRange(400, TIME_FRAME);
                var args = new PatternArgsItem(40, 60, start, end, TIME_FRAME);

                if (modelType is ElliottModelType.FLAT_EXTENDED
                              or ElliottModelType.TRIANGLE_CONTRACTING)
                {
                    args.Min -= args.Range;
                    args.Max += args.Range;
                }

                ModelPattern model = m_PatternGenerator.GetPattern(args, modelType);
                if (model.Candles.Count < 2) continue;

                var barsProvider = new TestBarsProvider(model.Candles);
                List<BarPoint> points = BuildPointsFromModel(model, barsProvider);
                if (points.Count < 2) continue;

                var markup = new ElliottWaveExactMarkup();
                List<ExactParsedNode> results = markup.Parse(points);

                foreach (ExactParsedNode result in results)
                    AssertSubWaveContinuity(result, modelType.ToString());
            }
        }

        /// <summary>
        /// Verifies that every result returned by <see cref="ElliottWaveExactMarkup.Parse"/>
        /// spans the full input point range — from <c>points[0].BarIndex</c> to
        /// <c>points[^1].BarIndex</c>.  Partial-span candidates that leave leading or
        /// trailing extrema unaccounted for must not appear in the results
        /// (§4.1-continuity hard rule).
        /// </summary>
        [Test]
        public void AllResultsSpanFullInputTest()
        {
            const int totalRuns = 10;

            for (int run = 0; run < totalRuns; run++)
            {
                (DateTime start, DateTime end) = Helper.GetDateRange(300, TIME_FRAME);
                var args = new PatternArgsItem(40, 60, start, end, TIME_FRAME);
                ModelPattern model = m_PatternGenerator.GetPattern(args, ElliottModelType.IMPULSE);

                if (model.Candles.Count < 2) continue;

                var barsProvider = new TestBarsProvider(model.Candles);
                List<BarPoint> points = BuildPointsFromModel(model, barsProvider);
                if (points.Count < 2) continue;

                int expectedStart = points[0].BarIndex;
                int expectedEnd   = points[^1].BarIndex;

                var markup = new ElliottWaveExactMarkup();
                List<ExactParsedNode> results = markup.Parse(points);

                foreach (ExactParsedNode result in results)
                {
                    Assert.AreEqual(
                        expectedStart, result.StartPoint.BarIndex,
                        $"[AllResultsSpanFull] run {run}: result starts at bar " +
                        $"{result.StartPoint.BarIndex} instead of {expectedStart} — " +
                        "partial-span candidate must be rejected (§4.1-continuity).");

                    Assert.AreEqual(
                        expectedEnd, result.EndPoint.BarIndex,
                        $"[AllResultsSpanFull] run {run}: result ends at bar " +
                        $"{result.EndPoint.BarIndex} instead of {expectedEnd} — " +
                        "partial-span candidate must be rejected (§4.1-continuity).");
                }
            }
        }
    }
}
