using NUnit.Framework;
using TradeKit.Core.AlgoBase;
using TradeKit.Core.Common;
using TradeKit.Core.ElliottWave;
using TradeKit.Core.Json;
using TradeKit.Core.PatternGeneration;

namespace TradeKit.Tests
{
    public class ExactMarkupTests
    {
        private PatternGenerator m_PatternGenerator;
        private static readonly ITimeFrame TIME_FRAME = TimeFrameHelper.Minute5;

        private class TestBarsProvider : IBarsProvider
        {
            private readonly List<JsonCandleExport> m_Candles;
            public TestBarsProvider(List<JsonCandleExport> candles)
            {
                m_Candles = candles;
            }

            public int Count => m_Candles.Count;
            public int StartIndexLimit => 0;
            public ITimeFrame TimeFrame => TIME_FRAME;
            public ISymbol BarSymbol => null!;

            public event EventHandler BarClosed { add { } remove { } }
            public double GetClosePrice(int index) => m_Candles[index].C;
            public double GetHighPrice(int index) => m_Candles[index].H;
            public int GetIndexByTime(DateTime dateTime) => m_Candles.FindIndex(c => c.OpenDate == dateTime);
            public double GetLowPrice(int index) => m_Candles[index].L;
            public double GetMedianPrice(int index) => (m_Candles[index].H + m_Candles[index].L) / 2;
            public double GetOpenPrice(int index) => m_Candles[index].O;
            public DateTime GetOpenTime(int index) => m_Candles[index].OpenDate;
            public void LoadBars(DateTime date) { }
            public void Dispose() { }
        }

        [SetUp]
        public void Setup()
        {
            m_PatternGenerator = new PatternGenerator(true);
        }

        /// <summary>
        /// Builds the list of BarPoints from a generated ModelPattern for use with ElliottWaveExactMarkup.
        /// Extracts main-level key points (level == model.Level) plus the pattern start point.
        /// </summary>
        private static List<BarPoint> BuildPointsFromModel(ModelPattern model, IBarsProvider barsProvider)
        {
            List<PatternKeyPoint> allKeyPoints = model.PatternKeyPoints
                .SelectMany(x => x.Value)
                .OrderBy(x => x.Index)
                .ToList();

            List<PatternKeyPoint> mainWaves = allKeyPoints
                .Where(x => x.Notation.Level == model.Level)
                .OrderBy(x => x.Index)
                .ToList();

            if (mainWaves.Count == 0)
                return new List<BarPoint>();

            PatternKeyPoint endNode = mainWaves.Last();
            bool isUp = endNode.Value > model.Candles[0].O;

            double startVal = isUp
                ? model.Candles.Take(mainWaves[0].Index + 1).Min(x => x.L)
                : model.Candles.Take(mainWaves[0].Index + 1).Max(x => x.H);

            int startIndex = model.Candles.FindIndex(
                x => Math.Abs(x.L - startVal) < double.Epsilon
                  || Math.Abs(x.H - startVal) < double.Epsilon);
            if (startIndex < 0)
                startIndex = 0;

            var points = new List<BarPoint>
            {
                new BarPoint(startVal, model.Candles[startIndex].OpenDate, barsProvider)
            };

            List<PatternKeyPoint> distinctPoints = allKeyPoints
                .Where(x => x.Index > startIndex && x.Index <= endNode.Index)
                .GroupBy(x => x.Index)
                .Select(g => g.OrderByDescending(x => x.Notation.Level).First())
                .OrderBy(x => x.Index)
                .ToList();

            foreach (PatternKeyPoint kp in distinctPoints)
                points.Add(new BarPoint(kp.Value, model.Candles[kp.Index].OpenDate, barsProvider));

            return points;
        }

        /// <summary>
        /// Generates <paramref name="totalTests"/> patterns of the given model type, runs
        /// ElliottWaveExactMarkup.Parse on the ideal key-points, and asserts that at least
        /// <paramref name="threshold"/> fraction of runs correctly identify the model.
        /// <para>
        /// Some model pairs are structurally indistinguishable in v1 (no sub-wave analysis):
        /// <list type="bullet">
        /// <item>DIAGONAL_CONTRACTING_INITIAL and DIAGONAL_CONTRACTING_ENDING share identical
        /// 5-wave price structure (both generated by the same GetDiagonal logic). They can only
        /// be distinguished by their sub-wave models (IMPULSE vs ZIGZAG inner waves), which is
        /// not evaluated in v1. Use <paramref name="acceptedTypes"/> to accept both.</item>
        /// <item>ZIGZAG and DOUBLE_ZIGZAG have the same 3-wave price structure and identical
        /// Fibonacci scoring in v1. Without parent context, both are valid interpretations.
        /// Use <paramref name="acceptedTypes"/> to accept both.</item>
        /// </list>
        /// </para>
        /// </summary>
        private void RunMarkupTest(
            ElliottModelType modelType,
            int totalTests = 20,
            int minBars = 200,
            double threshold = 0.6,
            ElliottModelType[]? acceptedTypes = null)
        {
            int matchedTests = 0;
            HashSet<ElliottModelType> accepted = acceptedTypes != null
                ? new HashSet<ElliottModelType>(acceptedTypes) { modelType }
                : new HashSet<ElliottModelType> { modelType };

            for (int i = 0; i < totalTests; i++)
            {
                (DateTime start, DateTime end) = Helper.GetDateRange(minBars, TIME_FRAME);
                PatternArgsItem paramArgs = new PatternArgsItem(40, 60, start, end, TIME_FRAME);

                // FLAT and TRIANGLE generators require room for the B-wave overshoot (B exceeds
                // the pattern origin) and for triangle wave A to extend beyond the endpoint.
                // PatternArgsItem sets Min=StartValue and Max=EndValue by default, which causes
                // the generator to fall back to Zigzag. Extend the price buffer so the generator
                // can produce genuine FLAT/TRIANGLE patterns.
                switch (modelType)
                {
                    case ElliottModelType.FLAT_EXTENDED:
                    case ElliottModelType.FLAT_RUNNING:
                    case ElliottModelType.TRIANGLE_CONTRACTING:
                    case ElliottModelType.TRIANGLE_RUNNING:
                        paramArgs.Min -= paramArgs.Range;
                        paramArgs.Max += paramArgs.Range;
                        break;
                }

                ModelPattern model = m_PatternGenerator.GetPattern(paramArgs, modelType);

                if (model.Candles.Count < 2)
                    continue;

                var barsProvider = new TestBarsProvider(model.Candles);
                List<BarPoint> points = BuildPointsFromModel(model, barsProvider);

                if (points.Count < 2)
                    continue;

                var markup = new ElliottWaveExactMarkup();
                List<ExactParsedNode> results = markup.Parse(points);
                ExactParsedNode? bestResult = results.FirstOrDefault();

                // Accept if the correct model appears anywhere in results with the right
                // wave count — meaning the hard rules were satisfied for the generated data.
                // Fibonacci ratios only affect ranking, not identification; a flat with
                // B/A=1.0 is valid (hard rules pass) even if it scores lower than a zigzag.
                ExactParsedNode? matchedResult = results.FirstOrDefault(
                    r => accepted.Contains(r.ModelType) && r.WaveCount == r.ExpectedWaves);
                bool matched = matchedResult != null;

                if (matched)
                {
                    matchedTests++;
                }
                else
                {
                    Console.WriteLine(
                        $"[{modelType}] run {i}: best={bestResult?.ModelType} " +
                        $"score={bestResult?.Score:F3} waves={bestResult?.WaveCount}/{bestResult?.ExpectedWaves}" +
                        $" | no {modelType} in results ({results.Count} total)");
                }
            }

            int minRequired = (int)Math.Ceiling(totalTests * threshold);
            Assert.IsTrue(
                matchedTests >= minRequired,
                $"[{modelType}] only {matchedTests}/{totalTests} runs matched " +
                $"(required ≥ {minRequired}, threshold {threshold:P0}).");
        }

        [Test]
        public void ImpulseExactMarkupTest() =>
            RunMarkupTest(ElliottModelType.IMPULSE, minBars: 300);

        [Test]
        public void DiagonalInitialExactMarkupTest() =>
            // INITIAL and ENDING share identical 5-wave price structure in v1;
            // both are accepted since they cannot be distinguished without sub-wave analysis.
            RunMarkupTest(ElliottModelType.DIAGONAL_CONTRACTING_INITIAL, minBars: 300,
                acceptedTypes: new[] { ElliottModelType.DIAGONAL_CONTRACTING_ENDING });

        [Test]
        public void DiagonalEndingExactMarkupTest() =>
            // INITIAL and ENDING share identical 5-wave price structure in v1;
            // both are accepted since they cannot be distinguished without sub-wave analysis.
            RunMarkupTest(ElliottModelType.DIAGONAL_CONTRACTING_ENDING, minBars: 300,
                acceptedTypes: new[] { ElliottModelType.DIAGONAL_CONTRACTING_INITIAL });

        [Test]
        public void ZigzagExactMarkupTest() =>
            // ZIGZAG and DOUBLE_ZIGZAG share identical 3-wave price structure and Fibonacci
            // scoring in v1; without parent context both are valid interpretations.
            RunMarkupTest(ElliottModelType.ZIGZAG, minBars: 200,
                acceptedTypes: new[] { ElliottModelType.DOUBLE_ZIGZAG });

        [Test]
        public void DoubleZigzagExactMarkupTest() =>
            // DOUBLE_ZIGZAG and ZIGZAG are indistinguishable in v1 (same 3-wave structure,
            // same Fibonacci maps). Without parent context, both are valid interpretations.
            RunMarkupTest(ElliottModelType.DOUBLE_ZIGZAG, minBars: 200,
                acceptedTypes: new[] { ElliottModelType.ZIGZAG });

        [Test]
        public void FlatExtendedExactMarkupTest() =>
            RunMarkupTest(ElliottModelType.FLAT_EXTENDED, minBars: 200);

        [Test]
        public void FlatRunningExactMarkupTest() =>
            RunMarkupTest(ElliottModelType.FLAT_RUNNING, minBars: 200);

        [Test]
        public void TriangleContractingExactMarkupTest() =>
            RunMarkupTest(ElliottModelType.TRIANGLE_CONTRACTING, minBars: 300);

        [Test]
        public void TriangleRunningExactMarkupTest() =>
            RunMarkupTest(ElliottModelType.TRIANGLE_RUNNING, minBars: 300);

        /// <summary>
        /// Generates a zigzag pattern built from specific sub-wave model types
        /// (A = IMPULSE, B = TRIANGLE_CONTRACTING, C = DIAGONAL_CONTRACTING_ENDING),
        /// runs the recursive markup, and verifies both the top-level model and that
        /// each sub-wave is identified as one of the expected types.
        /// </summary>
        [Test]
        public void ZigzagCompositeSubWaveMarkupTest()
        {
            const int totalTests = 10;
            int matchedTopLevel = 0;
            int matchedWaveA    = 0;
            int matchedWaveC    = 0;

            // Accepted sub-model sets: anything TargetModels supports for each position
            var acceptedA = new HashSet<ElliottModelType>
            {
                ElliottModelType.IMPULSE,
                ElliottModelType.DIAGONAL_CONTRACTING_INITIAL,
                ElliottModelType.DIAGONAL_CONTRACTING_ENDING
            };
            var acceptedC = new HashSet<ElliottModelType>
            {
                ElliottModelType.IMPULSE,
                ElliottModelType.DIAGONAL_CONTRACTING_ENDING,
                ElliottModelType.DIAGONAL_CONTRACTING_INITIAL
            };
            var acceptedTopLevel = new HashSet<ElliottModelType>
            {
                ElliottModelType.ZIGZAG, ElliottModelType.DOUBLE_ZIGZAG
            };

            for (int run = 0; run < totalTests; run++)
            {
                (DateTime start, DateTime end) = Helper.GetDateRange(2000, TIME_FRAME);
                PatternArgsItem args = new PatternArgsItem(40, 60, start, end, TIME_FRAME);
                args.Min -= args.Range;
                args.Max += args.Range;

                ModelPattern model = m_PatternGenerator.GetZigzagComposite(
                    args,
                    ElliottModelType.IMPULSE,
                    ElliottModelType.TRIANGLE_CONTRACTING,
                    ElliottModelType.DIAGONAL_CONTRACTING_ENDING);

                if (model.Candles.Count < 2) continue;

                var barsProvider = new TestBarsProvider(model.Candles);
                List<BarPoint> points = BuildPointsFromModel(model, barsProvider);
                if (points.Count < 2) continue;

                // Use no barsProvider so direction/candle hard rules are skipped
                // (same as existing tests — synthetic point data only).
                var markup = new ElliottWaveExactMarkup();
                List<ExactParsedNode> results = markup.Parse(points);

                ExactParsedNode best = results.FirstOrDefault(
                    r => acceptedTopLevel.Contains(r.ModelType)
                         && r.WaveCount == r.ExpectedWaves);

                if (best == null)
                {
                    Console.WriteLine(
                        $"[ZigzagComposite] run {run}: top={results.FirstOrDefault()?.ModelType}");
                    continue;
                }
                matchedTopLevel++;

                // Wave A (index 0): expected IMPULSE / DIAGONAL variants
                ElliottModelType waveAType = best.SubWaves?[0]?.ModelType
                    ?? ElliottModelType.SIMPLE_IMPULSE;
                if (acceptedA.Contains(waveAType))
                    matchedWaveA++;
                else
                    Console.WriteLine(
                        $"[ZigzagComposite] run {run}: wave A = {waveAType}");

                // Wave C (index 2): expected IMPULSE / DIAGONAL variants
                ElliottModelType waveCType = best.SubWaves?.Length >= 3
                    ? best.SubWaves[2]?.ModelType ?? ElliottModelType.SIMPLE_IMPULSE
                    : ElliottModelType.SIMPLE_IMPULSE;
                if (acceptedC.Contains(waveCType))
                    matchedWaveC++;
                else
                    Console.WriteLine(
                        $"[ZigzagComposite] run {run}: wave C = {waveCType}");
            }

            int minTopRequired = (int)Math.Ceiling(totalTests * 0.6);
            Assert.IsTrue(matchedTopLevel >= minTopRequired,
                $"[ZigzagComposite] top-level: {matchedTopLevel}/{totalTests} " +
                $"(required ≥ {minTopRequired}).");

            // Combined A+C identifications must reach 40% of top-level matches
            // (A and C have identical price structure to SIMPLE_IMPULSE in degenerate cases,
            //  so a soft combined threshold is the right check here).
            if (matchedTopLevel > 0)
            {
                int minSubRequired = (int)Math.Ceiling(matchedTopLevel * 0.4);
                Assert.IsTrue((matchedWaveA + matchedWaveC) >= minSubRequired,
                    $"[ZigzagComposite] combined sub-wave A+C identification too low: " +
                    $"A={matchedWaveA}, C={matchedWaveC}, sum={matchedWaveA + matchedWaveC} " +
                    $"of {matchedTopLevel} top-level matches (required ≥ {minSubRequired}).");
            }
        }
    }
}
